---
- name: Lister les groupes d'hôtes existants
  ansible.builtin.uri:
    url: "{{ centreon_hosts_api_url }}?action=action&object=centreon_clapi"
    validate_certs: "{{ centreon_hosts_validate_certs }}"
    method: POST
    headers: "{{ _centreon_hosts_headers }}"
    body_format: json
    body:
      action: show
      object: HG
    return_content: true
    timeout: "{{ centreon_hosts_api_timeout }}"
  register: _centreon_hosts_hg_existing
  changed_when: false

- name: Créer les groupes d'hôtes manquants
  ansible.builtin.uri:
    url: "{{ centreon_hosts_api_url }}?action=action&object=centreon_clapi"
    validate_certs: "{{ centreon_hosts_validate_certs }}"
    method: POST
    headers: "{{ _centreon_hosts_headers }}"
    body_format: json
    body:
      action: add
      object: HG
      values: "{{ item }};{{ item }}"
    return_content: true
    timeout: "{{ centreon_hosts_api_timeout }}"
  loop: "{{ _centreon_hosts_required_hostgroups }}"
  when: item not in (_centreon_hosts_hg_existing.json.result | default([]) | map(attribute='name', default='') | select | list)
  register: _centreon_hosts_hg_created
  changed_when: true
