[snmp_servers]
srv-prod-01 ansible_host=10.10.1.11
srv-prod-02 ansible_host=10.10.1.12
srv-prod-03 ansible_host=10.10.1.13

[snmp_servers:vars]
ansible_user=deploy
ansible_become=true
ansible_become_method=sudo
